language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
gemfile: Gemfile
notifications:
  recipients:
    - ben.biddington@gmail.com
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"